#!/bin/bash
set -e


echo "Updating repositories"
add-apt-repository ppa:webupd8team/java 
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
apt-get update -qq
apt-get install -qy git oracle-java8-installer maven

echo "Configuring user environment"
bash_profile=/home/vagrant/.bash_profile
su vagrant -c cat <<EOF > /home/vagrant/.ssh/config
Host github.com
	StrictHostKeyChecking no 

EOF
chown -R vagrant:vagrant /home/vagrant
#su vagrant -c /vagrant/script/bin/lr-bootstrap

cat <<EOF > ${bash_profile}
export WORKON_HOME=${WORKON_HOME}
export PATH=/vagrant/script/bin:${PATH}

source /usr/local/bin/virtualenvwrapper.sh
alias ls="ls -F"
cd /vagrant
EOF


# echo "Configuring /etc/hosts"
# ETCHOSTS=`cat /tmp/etchosts`

# cat <<EOF > /etc/hosts
# ::1 ip6-localhost ip6-loopback
# fe00::0 ip6-localnet
# ff00::0 ip6-mcastprefix
# ff02::1 ip6-allnodes
# ff02::2 ip6-allrouters
# ff02::3 ip6-allhosts
# 0.0.0.0  sor-dev 
# 172.16.42.42 sor-dev

# EOF

# rm -f /tmp/etchosts

