#!/bin/bash
set -e

sor_package_path="uk/gov/gds/sor"

function start_app {
	local app_name=$1
	local app_version=$2 
	local app_jar="/vagrant/${app_name}/target/${app_name}-${app_version}.jar"

	echo "Starting app ${app_name} from ${app_jar}"
	java -jar ${app_jar}
}